language: ruby
bundler_args: --jobs 4 --retry 3 --without integration
rvm:
- 1.9.3
- 2.0.0
- 2.1.5
script:
- bundle exec rake rubocop
- bundle exec rake foodcritic
- bundle exec rake chefspec
- bundle exec rake kitchen:all
env:
  matrix:
  - CHEF_VERSION: "10.30"
  - CHEF_VERSION: "11.16"
  - CHEF_VERSION: "12.00"
sudo: false
cache: bundler
